# Generated by Django 5.1.6 on 2025-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
