# Generated by Django 5.1.6 on 2025-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_job_alter_jobseekerprofile_full_name_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
