# Generated by Django 5.1.6 on 2025-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_jobseekerprofile_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('remote', 'Remote'), ('internship', 'Internship')], max_length=50),
        ),
    ]
