# Generated by Django 5.1.6 on 2025-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_jobseekerprofile_email_alter_jobseekerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
