# Generated by Django 5.1.6 on 2025-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_job_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='experience_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
